### ISSUE TITLE
<js.Undefined> != js.Undefined ?!?

### ISSUE THREAD

**Issue by jedie** [rfk/pypyjs#120]
In my pypyjs_mandelbrot.py example ( https://gist.github.com/jedie/f3b59ce35434dd92130f ) i must use the ugly work-a-round: **if repr(canvas) == "<js.Undefined>":**

See testcode:
```
import js

undefined_handle = js.globals["$"]("#not_exists")
print repr(undefined_handle)

undefined_element = undefined_handle[0]
print repr(undefined_element)

print repr(js.Undefined)
print repr(js.Undefined) == "<js.Undefined>" # ugly work-a-round
print undefined_element == js.Undefined # TypeError: could not convert py type to js type
```
output is:
```
<js.Object handle=11>
<js.Undefined>
<type 'Undefined'>
False
Traceback (most recent call last):
  File "c callback", line 12, in <module>
  File "<string>", line 11, in <module>
TypeError: could not convert py type to js type
```

**Comment by rfk** [comment]
Try using `js.undefined` which is a (singleton) intance of the `js.Undefined` type.  I agree this is needlessly confusing!

**Comment by jedie** [comment]
Yes **undefined_element == js.undefined** worked. And yes, this is confusing ;)

**Comment by jedie** [comment]
btw. the js module contains both objects: **'Undefined'** and **'undefined'**
```
>>> import js
>>> dir(js)
['Array', 'Boolean', 'Error', 'Function', 'Method', 'Number', 'Object', 'String', 'Undefined', 'Value', '__doc__', '__name__', '__package__', 'bind', 'convert', 'equal', 'eval', 'false', 'globals', 'instanceof', 'new', 'null', 'true', 'uint32', 'undefined', 'urshift']
>>> 
```

btw. where is the sourcecode of the js module?!?

**Comment by kirbyfan64** [comment]
[deps/pypy/pypy/module/js](https://github.com/rfk/pypy/tree/master/pypy/module/js)

**Comment by jedie** [comment]
Thanks!

**Comment by tritium21** [comment]
because Undefined is a type, and undefined is an instance?  like NoneType and None are separate, but related objects in python.

**Comment by jedie** [comment]
Then, why not **UndefinedType** and **Undefined** ?

**Comment by tritium21** [comment]
I would assume because it is in the javascript side of the world, and javascript does not have a rich tradition of sane naming schemes?

**Comment by rfk** [comment]
There's not a lot of consistency in naming types in python either, e.g. `NoneType` versus `str`.  Frankly I didn't think of `UndefinedType` when I was making this API, but I agree it would probably be a lot less confusing.  What do you think about e.g. `js.String` versus `js.StringType` by comparison?

(as they say, there are only two hard problems in computer science: cache invalidation, and naming things)

**Comment by jedie** [comment]
>  What do you think about e.g. js.String versus js.StringType by comparison?
For me it seems js.StringType is better, isn't it?

**Comment by rfk** [comment]
If you want to explicitly create a javscript string though, ISTM that `js.String("foobar")` reads better than `js.StringType("foobar")`.  It may be worth renaming `Undefined` to `UndefinedType` and just accepting that it's inconsistent with the other types in the module, because it's really the only one that's confusing in its current incarnation.
