### ISSUE TITLE
JIT causes unpredictable slowness

### ISSUE THREAD

**Issue by perkinslr** [rfk/pypyjs#128]
I've got two examples where the JIT version is painfully slow while the non-JIT version is much faster.  The first, and simpler, is objgraph.show_growth, which iterates over all the non-gcable items from the gc module and counts them.  Later invocations compare the number from the previous call in order to help identify object leaks.  Sometimes when called in the JIT version, it returns quickly, less than a second.  Other times, it takes several minutes to run, with little in between.  

The second example is the schemepy repl, slightly modified to use a generator pattern and setTimeout to avoid ever blocking.  It uses a single loop to interpret scheme syntax, which yields every 100ms, and is continued via next as soon as pending js events have cleared (1ms minimum).  Similarly to objgraph, the JIT build sometimes hangs during iteration, and sometimes runs full speed.  It doesn't seem to matter how many iterations are in play, since (fact 3) sometimes takes several minutes to run, and only needs to iterate a dozen or so times, and (fact 10000) sometimes returns quickly.  The non-jit build runs slower, but the time taken seldom varies by more than a couple percent.  

The obvious similarity between these two is the iteration over large lists, which may be related to #11, but unlike #11, Firefox has substantially fewer problems than Chromium with both schemepy and objgraph.

**Comment by kirbyfan64** [comment]
Does PyPy itself exhibit something similar? My guess would just be that, since sometimes the JIT version actually is faster, you're seeing the JIT warmup time or something.

**Comment by perkinslr** [comment]
Looks like you're probably right, I was underestimating the time the JIT needed to work.  I ran (fact 1000) 2 times, then let it sit for about half an hour and now it's taking a reasonable amount of time, about 3x CPython's speed.  Would be nice if there was some way to cache the JITed versions of the functions...

**Comment by rfk** [comment]
I suspect you're seeing the very large compilation overhead of the current asmjs JIT engine.  There's a similar effect with e.g. the richards benchmark in the suite here:

  http://arewepythonyet.com/performance.html#benchmark=richards

Scroll down to the last graph on that page, which shows the performance of each run over a series of 20 consecutive runs.  The baseline performance is pretty OK, but there are *huge* spikes when the JIT kicks in.  It's noticeable on Firefox but really really costly under Chrome.

My current theory is based on just generating too much code all at once.  Whenever the PyPy JIT kicks in and asks us to add some more JITed code to a loop, we currently recompile *all* of the generated code for that loop, including any code that we were already running.  Over time, as more paths through the code are discovered, the amount of JITed code grows bigger and the time we spend recompiling it grows longer.

This is particularly bad in Chrome, because when we re-compile we throw away all of the work that the V8 JIT has done on the previous version, forcing it to start from scratch.

The solution is to try to generate the JITed code in smaller chunks, and try to avoid recompiling things if we don't need to.  I expect this to slightly decrease the steady-state performance because it will increase call overhead between the chunks, but will probably be worth it overall.  It'll be a pretty serious refactor of the asmjs JIT backend, but that code needs a good refactor anyway :-)

**Comment by perkinslr** [comment]
That makes sense; there are lots of good targets for the JIT in the scheme interpreter, which it relies on to be remotely competitive with mainstream scheme implementations.  

Even giving the JIT lots of time and iterations to run, objgraph.show_growth remains slow, and it's actual code path is pretty short, but since it interacts with the gc module it could be having a similar issue when the JIT works on other stuff.  

If I understand how the PyPy JIT works, it outputs asmjs, which is then JITed by the js engine.  How hard would it be to cache the generated asmjs?  I know it's somewhat unusual to do so since it won't do any good if the usage pattern changes, but anytime there is a main loop, like twisted's reactor, some of the optimisations are going to be the same every time.

**Comment by rfk** [comment]
>  How hard would it be to cache the generated asmjs?

Nigh impossible currently; PyPy's traces embed lots of stuff that can change from one run to the next, e.g. raw memory addresses of objects being operated on.  I remember seeing some discussion of generating more cachable JIT traces on the PyPy list a while back, and if they enable that work in native pypy, we should certainly try to leverage it here.

**Comment by perkinslr** [comment]
That is unfortunate, but not really a surprise, caching JITs are hard to implement.  Also, running more than a hundred calls to objgraph.show_growth finally showed a noticeable improvement in time taken, so I think it was just slower/more complicated to JIT.  I also don't suppose there is a way to either focus the JIT's attention on something in particular, so that it doesn't have to keep coming back to it, or to tell the JIT to not try to mess with a function or module?  The non JIT version is fast enough for the scheme interpreter to be usable, so I'll probably just go that route, but having the JIT for stuff outside the main interpreter would still be useful.

**Comment by jedie** [comment]
I add my Mandelbrot example with kit and without jit here:

https://jedie.github.io/pypyjs-examples/mandelbrot.html
https://jedie.github.io/pypyjs-examples/mandelbrot-nojit.html

The difference is not very mutch. ~20sec (+jit) vs. 26sec (without jit)

**Comment by perkinslr** [comment]
That's kinda to be expected on a single run, have it generate a dozen sets and compare the total time, and the time for just the last run.

**Comment by perkinslr** [comment]
So I just got around to re-investigating this with the latest pypyjs build.  The good news is that the JITs don't seem to be fighting quite as badly, the scheme interpreter can handle repeated `(fact 100)` calls without as many major lag spikes.  On the other hand, `objgraph.show_growth` now causes the following crash.

    Uncaught (in promise) abort() at Error
    at jsStackTrace (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0),    <anonymous>:1:20654)
    at stackTrace (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:1:20837)
    at Object.abort (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:86:31988)
    at _abort (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:1:172444)
    at Ded (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:78:1023668)
    at $wb (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:75:65230)
    at xUa (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:76:78459)
    at wUa (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:76:38785)
    at iXc (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:71:222984)
    at HTa (eval at FunctionPromise (http://127.0.0.1:8082/lib/FunctionPromise.js:1:0), <anonymous>:78:991865)
    If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.

The non-jit version still works as expected.
