### ISSUE TITLE
Iterating over js.globals locks interpreter

### ISSUE THREAD

**Issue by brianv0** [rfk/pypyjs#85]
I'm not sure what's happening, but the following code ends up dying:

```
import js
[i for i in js.globals]
```

This message is thrown out into Chrome:
```
Uncaught (in promise) abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 134217728, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.") at Error
    at jsStackTrace (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:1:20962)
    at stackTrace (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:1:21145)
    at abort (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:24:31767)
    at enlargeMemory (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:1:21608)
    at Function.Runtime.dynamicAlloc (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:1:6810)
    at _sbrk (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:1:167554)
    at TEd (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:17:237096)
    at y8c (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:9:1618253)
    at Iod (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:9:837720)
    at Array.Vg (eval at <anonymous> (http://pypyjs.org/js/pypy.js-0.2.0/lib/pypy.js:225:15), <anonymous>:14:48534)
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
```

**Comment by rfk** [comment]
Thanks for the report, this traceback usually means something has gone haywire and consumed all the memory available to the emscripten-compiled VM.  There certainly shouldn't be enough items in `js.globals` to exhaust memory so it's probably a bug in my iterator implementation.

**Comment by rfk** [comment]
Indeed it doesn't seem to be specific to `js.globals`, e.g.:
```
>>> v = js.Object()
>>> v["hello"] = "world"
>>> [i for i in v]
*crashes out with similar traceback*
```

**Comment by rfk** [comment]
It turns out that I haven't actually implemented iteration over `js.Object` keys, so pypy is falling back to its default sequence-iteration protocol: starting at zero, loop over the positive integers until it finds one that's not in the sequence.  Unfortunately `js.globals[x] == js.undefined` for all integers `x`, so it tries to build up an infinite list, and eventually crashes when out of memory.

I'm taking a look at implementing proper object iteration now.

**Comment by rfk** [comment]
This should be fixed by https://github.com/rfk/pypy/commit/df3362e4f50f5d195d883f6214036a382bfb405f
