### ISSUE TITLE
datetime.now raises ValueError because of ms

### ISSUE THREAD

**Issue by horejsek** [rfk/pypyjs#86]
```python
>>> datetime.datetime.now()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/pypyjs/lib_pypy/datetime.py", line 1548, in now
    return cls.fromtimestamp(t, tz)
  File "/lib/pypyjs/lib_pypy/datetime.py", line 1522, in fromtimestamp
    result = cls(y, m, d, hh, mm, ss, us, tz)
  File "/lib/pypyjs/lib_pypy/datetime.py", line 1459, in __new__
    hour, minute, second, microsecond)
  File "/lib/pypyjs/lib_pypy/datetime.py", line 312, in _check_time_fields
    raise ValueError('microsecond must be in 0..999999', microsecond)
ValueError: ('microsecond must be in 0..999999', -911000)
```

**Comment by rfk** [comment]
Thanks for the report.  I wasn't able to reproduce this in my own testing, but I guess it could easily be a bug that only triggers at certain times or under certain circumstances.  Are you able to consistently reproduce?

**Comment by elgertam** [comment]
I am seeing this too, but only in Chrome on OS X.

Safari and Firefox on OS X behave as designed/expected, as do Chrome and Firefox on Windows. (IE11, of course, doesn't even bring up the loading message.)

**Comment by horejsek** [comment]
I can always reproduce it on my Mac with Chrome and on my Chromebook Pixel.
